version: "3"
services:
  app:
    container_name: enker-svc
    environment:
      - MONGO_HOST=mongo
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
      container_name: mongo
      image: mongo
      environment:
        - MONGO_INITDB_DATABASE=tumo
      volumes:
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
          - "27017:27017"
